apiVersion: batch/v1
kind: Job
metadata:
  name: jmeter-slaves
  labels:
    jmeter_mode: slave
spec:
  ttlSecondsAfterFinished: 60
  backoffLimit: 0
  parallelism: 0
  template:
    metadata:
      labels:
        jmeter_mode: slave
    spec:
      containers:
      - name: jmslave
        image: rbillon59/jmeter-k8s-base:5.4.1
        imagePullPolicy: Always
        env:
        - name: MODE
          value: "SLAVE"
        command: ["/bin/bash"]
        args: ["-c", "trap 'exit 0' SIGUSR1 && while true; do sleep 30;done"]
        ports:
        - containerPort: 1099
        - containerPort: 50000
        - containerPort: 4445
        resources:
          requests:
            memory: "1024Mi"
            cpu: "1024m"
          limits:
            memory: "1024Mi"
            cpu: "1024m"
        livenessProbe:
          exec:
            command:
            - cat
            - /opt/jmeter/apache-jmeter/bin/jmeter
      restartPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: jmeter-slaves-svc
  labels:
    jmeter_mode: slave
spec:
  clusterIP: None
  ports:
    - port: 1099
      name: jmeter
      targetPort: 1099
    - port: 50000
      name: rmi
      targetPort: 50000
    - port: 4445
      name: stoptest
      targetPort: 4445
  selector:
    jmeter_mode: slave
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cleaner
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: my-completed-jobs-cleaner-role
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-completed-jobs-cleaner-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: my-completed-jobs-cleaner-role
subjects:
- kind: ServiceAccount
  name: cleaner
  namespace: default
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: jobs-cleanup
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: cleaner
          containers:
          - name: kubectl-container
            image: bitnami/kubectl:latest
            command: ["sh", "-c", "kubectl delete jobs --selector jmeter_mode=slave --field-selector status.successful=1 && kubectl delete jobs --selector jmeter_mode=master --field-selector status.successful=1"]
          restartPolicy: Never